import React from 'react';
import Head from 'next/head';
import styles from '../styles/About.module.css'



function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <div className={styles.main}>
            <div className=  {styles.infocontainer} >
                <div className={styles.devInfo} >
                    <div className={styles.hello}>Hii i'am</div>
                    <div className={styles.name}>Abhishek kumar</div>
                    <div className={styles.about}>developer,coder,writter</div>
                    {/* <div className="buttons">
                        <button className="cv">  Download cv  <a href=""  </a></button>
                        <button>Contact me</button>
                    </div> */}

                </div>
                {/* <div className="devImg"> <img src="human.png" alt=""></div> */}
            </div>
        </div>


      </div>
    </>
  )
}

export default About
