import React, { useState } from 'react'
import Head from 'next/head';
import styles from '../styles/Contact.module.css'




function Contact() {
  const [name, setname] = useState('')
  const [email, setemail] = useState('')
  const [desc, setdesc] = useState('')
  const [phone, setphone] = useState('')

  const handlesubmit = (e) => {
    e.preventDefault()

    const data = { name, email, desc, phone };

    fetch('http://localhost:3000/api/postcontact', {
      method: 'POST', // or 'PUT'
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    })
      .then(response => response.text())
      .then(data => {
        console.log('Success:', data);
        alert("Thanks for contacting us ");
        setname('')
        setemail('')
        setdesc('')
        setphone('')
      })
      .catch((error) => {
        console.error('Error:', error);
      });
  }

  const handlechange = (e) => {
    if (e.target.name == "phone") {
      setphone(e.target.value)
    }
    if (e.target.name == "name") {
      setname(e.target.value)
    }
    if (e.target.name == "email") {
      setemail(e.target.value)
    }
    if (e.target.name == "desc") {
      setdesc(e.target.value)
    }
  }


  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <h1>contact us </h1>
        <form onSubmit={handlesubmit}>
          <div className={styles.form}>
            <label className={styles.lebel} htmlFor="name">Enter your Name : </label>
            <input type="text" value={name} onChange={handlechange} className={styles.control} id="name" name="name" aria-describedby="emailHelp" placeholder="Enter your name " required />
          </div>
          <div className={styles.form}>
            <label className={styles.lebel} htmlFor="email">Email address : </label>
            <input type="email" value={email} onChange={handlechange} className={styles.control} id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email" required />
          </div>
          <div className={styles.form}>
            <label className={styles.lebel} htmlFor="phone">phone number : </label>
            <input type="phone" value={phone} onChange={handlechange} className={styles.control} id="phone" name="phone" aria-describedby="emailHelp" placeholder="phone number" required />
          </div>
          <div className={styles.form}>
            <label className={styles.lebel} htmlFor="desc">Eleborate your concern : </label>
            <textarea className={styles.control} type="text" value={desc} onChange={handlechange} name='desc' placeholder="write your concern here" id="dcsc" />
          </div>

          <button type="submit" className={styles.button}>Submit</button>
        </form>
      </div>
    </>
  )
}

export default Contact
