import Head from 'next/head'
import Image from 'next/image';
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size:40px;
        }
        `}
      </style>


      <Head>
        <title>Coders_bog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hunding coder
        </h1>
        <div className={styles.imageWarpper}></div>
        <Image className={styles.myImg} src="/laptop 2.jpg" width={225} height={207}></Image>

        <p className={styles.description}>
          Blogs form coders to coder
        </p>
        <div><h2>Popular Blogs</h2></div>
        <div className="bolgs">
          <div className="blogItem">
            <h3>
              How to learn javaScript
            </h3>
            <p>javaScript is a language for the web developement and for various porpus</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3>
              How to learn javaScript
            </h3>
            <p>javaScript is a language for the web developement and for various porpus</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3>
              How to learn javaScript
            </h3>
            <p>javaScript is a language for the web developement and for various porpus</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>


      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
